### ISSUE TITLE
Is this part of code necessary?

### ISSUE THREAD

**Issue by mcdonamw** [anwather/ReconcileTagNames#1]
I was wondering if this part of the code is necessary.  It doesn't seem to ever evaluate.  Which is a good thing as why would we want to delete a correct tag?

```
elseif (!($tag.Name -in $tagCorrections)) {
     Write-Output "Correct Tag already exists"
     $obj = [PsCustomObject]@{
           id      = $id.ResourceId
           action  = "Remove"
           tagName = $tag.Name
     }
     $actions += $obj
}
```

**Comment by anwather** [comment]
You know what - I'm not sure why that is there. I haven't looked at this script for a while - maybe there was a reason for it that didn't pan out? I'll have a look and see if I can work out what I was trying to do.

**Comment by anwather** [comment]
Ok - its for when a resource has multiple tags on it that are incorrect - i.e. a resource that is tagged with ```costCenter``` and ```Cost Center``` when it should be only tagged with ```costcentre```
